apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace_name }}
spec:
  controlPlaneRef:
    apiGroup: infrastructure.cluster.x-k8s.io    # no version here
    kind: VCluster
    name: {{ .Values.cluster_name }}
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io    # no version here
    kind: VCluster
    name: {{ .Values.cluster_name }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace_name }}
spec:
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: {{ .Values.vcluster_version }}
    values: |-
      sync:
        fromHost:
          nodes:
            enabled: true
      controlPlane:
        distro:
          k8s:
            enabled: false
            version: ""
            imagePullPolicy: ""
            image:
              registry: ghcr.io
              repository: "loft-sh/kubernetes"
              tag: {{ .Values.kubernetes_version }}
        statefulSet:
          resources:
            limits:
              cpu: 250m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
      policies:
        limitRange:
          enabled: false
        resourceQuota:
          enabled: true
          quota:
            requests.cpu: {{ add .Values.cluster_cpu 200 | add 1000 }}m
            requests.memory: {{ add .Values.cluster_ram 256 | add 1536 }}Mi
            limits.cpu: {{ add .Values.cluster_cpu 200 | add 3000 }}m
            limits.memory: {{ add .Values.cluster_ram 2048 | add 4352 }}Mi
            requests.storage: {{ .Values.cluster_storage }}Gi
