apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace_name }}
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{ .Values.cluster_name }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{ .Values.cluster_name }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace_name }}
spec:
  # controlPlaneEndpoint:
  #   host: ""
  #   port: 0
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: {{ .Values.vcluster_version }}
    values: |-
      sync:
        fromHost:
          nodes:
            enabled: true
      controlPlane:
        statefulSet:
          resources:
            limits:
              cpu: 250m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
      policies:
        limitRange:
          enabled: false
        resourceQuota:
          enabled: true
          quota:
            requests.cpu: {{ add .Values.cluster_cpu 200 | add 1000 }}m # required + 200m for controlPlane + 550m for arc
            requests.memory: {{ add .Values.cluster_ram 256 | add 1536 }}Mi # required in Mi + 256Mi for controlPlane + 1393Mi for arc
            limits.cpu: {{ add .Values.cluster_cpu 200 | add 3000 }}m # required + 200m for controlPlane + 1770m for arc
            limits.memory: {{ add .Values.cluster_ram 2048 | add 4352 }}Mi # required + 2Gi for controlPlane + 4350Mi for arc
            requests.storage: {{ .Values.cluster_storage }}Gi
      