name: Arc Onboarding
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Name of the Kubernetes cluster (must match created vCluster)'
        required: true
      namespace_name:
        description: 'Namespace inside the cluster'
        required: true
 
jobs:
  deploy-vcluster:
    environment: aks
    runs-on: [self-hosted, Linux]
    defaults:
      run:
        shell: bash  # Changed from pwsh
    env:
      CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}
      NAMESPACE_NAME: ${{ github.event.inputs.namespace_name }}
      RESOURCE_GROUP: AzureArcVClusterTest
      LOCATION: WestUS3
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  
 
      - name: Apply Azure Arc Namespaces and LimitRange
        run: |
          echo "Connecting to vCluster in background mode..."
          vcluster connect "$CLUSTER_NAME" -n "$NAMESPACE_NAME" --background-proxy=false
          echo "Applying arc-ns YAML..."
          kubectl --kubeconfig ~/.kube/config-vcluster_"$CLUSTER_NAME"_"$NAMESPACE_NAME" apply -f ./arc-ns
          echo "Namespace and LimitRange applied in vCluster."

      - name: Create Resource Group in Azure (if not exists)
        run: |
          echo "Creating Azure resource group '$RESOURCE_GROUP'..."
          az group create \
            --name "$RESOURCE_GROUP" \
            --location "$LOCATION" \
            --output table
          echo "Azure resource group '$RESOURCE_GROUP' ensured."
 
      - name: Connect Kubernetes Cluster to Azure Arc
        run: |
          echo "Connecting vCluster to Azure Arc..."
          vcluster connect "$CLUSTER_NAME" -n "$NAMESPACE_NAME" -- \
            az connectedk8s connect \
              --name "$CLUSTER_NAME" \
              --resource-group "$RESOURCE_GROUP"
          echo "vCluster successfully connected to Azure Arc."